INSERT INTO PATIENT 
				(FULL_NAME, DATE_OF_BIRTH, IDENTIFICATION, TYPE_IDENTIFICATION, HEALTHCARE_PROVIDER, CLINIC_HISTORY) VALUES 
				("Jose", "2002-02-01", "122323232", "Cedula", "Famisanar", "Brazo Roto");
				
INSERT INTO PATIENT 
				(FULL_NAME, DATE_OF_BIRTH, IDENTIFICATION, TYPE_IDENTIFICATION, HEALTHCARE_PROVIDER, CLINIC_HISTORY) VALUES 
				("Brayan", "2002-02-01", "122323232", "Cedula", "Compensar", "Pie Roto");
				
INSERT INTO PATIENT 
				(FULL_NAME, DATE_OF_BIRTH, IDENTIFICATION, TYPE_IDENTIFICATION, HEALTHCARE_PROVIDER, CLINIC_HISTORY) VALUES 
				("Carlos", "2002-02-01", "122323232", "Cedula Extranjera", "Colsanitas", "Clavicula Roto");
				
INSERT INTO PATIENT 
				(FULL_NAME, DATE_OF_BIRTH, IDENTIFICATION, TYPE_IDENTIFICATION, HEALTHCARE_PROVIDER, CLINIC_HISTORY) VALUES 
				("Rodolfo", "2002-02-01", "122323232", "Cedula", "Compensar", "Pie Roto");