INSERT INTO PATIENT 
				(FULL_NAME, DATE_OF_BIRTH, IDENTIFICATION, TYPE_IDENTIFICATION, HEALTHCARE_PROVIDER, CLINIC_HISTORY) VALUES 
				("Jose", "2002-02-01", "122323232", "Cedula", "Famisanar", "Brazo Roto");